### PR TITLE
Further customize `options.replacement`

### PR DESCRIPTION
**Pull request by pillowfication**
Similar to #26, I needed more customizable replacements for invalid characters. I've added the code I'm currently using, as a suggested update.

```javascript
const SANITIZE_MAP = [
  ['/', '-'],
  ['\\', '-'],
  ['?', ''],
  ['*', 'x'],
  [':', '-'],
  ['|', '-'],
  ['<', '_'],
  ['>', '_'],
  [/^\s+|\s+$/g, '_']
];

const filename = '\\<foo:bar|baz>/quuz?hello * world/   ';

sanitizeFilename(filename, {replacementMap: SANITIZE_MAP});
-> '-_foo-bar-baz_-quuzhello x world-_'
```

### CODE REVIEW

**Comment by joelmukuthu** [comment]
This looks really nice. I guess we could build upon the `replacement` option and allow it to be an object or array as well. Being a user-facing option, I'm more inclined toward making things verbose with an object instead:

```js
sanitize(filename, {
  replacement: {
   { pattern: '/', replacement: '-' },
   { pattern: /^\s+|\s+$/g, replacement: '_' },
   { pattern: '*', replacement: '' } // support * as a catch-all pattern
  }
})
```
Thoughts, @parshap and @pillowfication?

**Comment by pillowfication** [comment]
@joelmukuthu The catch-all should be specified another way to support when you want to match the `*` character.

```javascript
sanitize('foo*bar///', {replacement: [
  {pattern: '*', replacement: 'x'},
  {pattern: sanitize.CATCH_ALL, replacement: '_'}
]});
-> 'fooxbar___';
```

In this PR, by leaving the original `options.replacement` untouched, you can do it like

```javascript
sanitize('foo*bar///', {
  replacement: '_', // This is the catch-all
  replacementMap: [
    {pattern: '*', replacement: 'x'}
  ]
});
-> 'fooxbar___';
```

**Comment by parshap** [comment]
This is a good feature. I'd lean towards a simple object map:

```js
{
  '/', '-',
  '\\', '-',
  '?', '',
}
```

I know this doesn't allow for using a regex pattern, but I'm not sure if that's really needed?
 Alternatively, what if it took a function that allowed the end user to implement whatever logic they wanted to determine the replacement character?

**Comment by parshap** [comment]
Turns out you can already pass in a function that will get called with the part that is getting replaced! This is thanks to [`String.prototype.replace`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter). What do you guys think about this?

You could achieve the original example with:

```javascript
const SANITIZE_MAP = [
  ['/', '-'],
  ['\\', '-'],
  ['?', ''],
  ['*', 'x'],
  [':', '-'],
  ['|', '-'],
  ['<', '_'],
  ['>', '_'],
  [/^\s+|\s+$/g, '_']
];

const filename = '\\<foo:bar|baz>/quuz?hello * world/   ';

sanitizeFilename(filename, {
  replacement: function(val) {
    for (var i = 0; i < SANITIZE_MAP.length; i++) {
      if (SANITIZE_MAP[i][0].test(val)) {
        return SANITIZE_MAP[i][1];
      }
    }
  },
});
-> '-_foo-bar-baz_-quuzhello x world-_'
```

**Comment by joelmukuthu** [comment]
Right! +1 for the function, then we just need to update the documentation :)

**Comment by pillowfication** [comment]
Sick. Looks like this wasn't needed.

**Pull request closed without merging**
