### PR TITLE
Added MIT License

### PR DESCRIPTION
**Pull request by mcilroyc**
Would you consider using the MIT license, or perhaps allowing a dual license (MIT & WTFPL)?

### CODE REVIEW

**Comment by parshap** [comment]
Sure. Does the WTFPL not meet your needs?

**Comment by mcilroyc** [comment]
I think *functionally* WTFPL is sufficient, but MIT is more readily recognized (to wit: already cleared by lawyer-types).  In any case, having a LICENSE file in the repo is helpful.

**Comment by parshap** [comment]
I've licensed under WTFPL or ISC and added the license text in https://github.com/parshap/node-sanitize-filename/commit/dff231684c60f4bcf5271c5abe77aed8872159ab. Let me know if you need anything else!

**Comment by mcilroyc** [comment]
thanks.

**Pull request closed without merging**
