### PR TITLE
Fix TypeScript default export

### PR DESCRIPTION
**Pull request by zac1st1k**
To fix the TypeScript import issue as shown below

image

### CODE REVIEW

**Comment by papb** [comment]
Instead of this PR, I think you should just use the following syntax instead:

```ts
import sanitizeFilename = require('sanitize-filename')
```

This syntax is becoming the norm now for modules with a 'default' export that also wish to be compatible with CommonJS require style.

Please try that, it should work :)

**Comment by zac1st1k** [comment]
Hi @papb ,

I see what you meant, yes it's working. I amended my PR to add namespace import in order to support `import * as sanitizeFilename from 'sanitize-filename';`, which is kinda consistent with most libraries and doesn't break existing signature. what do you think?

**Comment by papb** [comment]
To be honest, I don't know, ultimately it will be up to the repository owner, of course. However, since the day I learned this `import = require` syntax, I have never used `import *` anymore. Never needed it. I have also seen some criticism to using default exports, and I am also a bit biased given that [sindresorhus](http://github.com/sindresorhus) does not support default exports in any of his packages and advocates simply using `import = require` instead. I really like his work so I might be quite biased here...

**Comment by zac1st1k** [comment]
Yes, fair enough. I am closing this PR. Thanks for your review!

**Pull request closed without merging**
